# Generated by Django 3.0.7 on 2020-06-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidatejobmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='mobile',
            field=models.CharField(default=True, max_length=11),
        ),
    ]
